// Generated by CoffeeScript 1.3.3

/*
	Project: CurrencyConverter
	File: app.js
	Author : Vetri
*/


(function() {
  var CurrencyConverter;

  CurrencyConverter = (function() {

    function CurrencyConverter() {}

    CurrencyConverter.prototype.init = function() {
      fx.base = "USD";
      fx.rates = {
        "EUR": 0.74510096,
        "GBP": 0.64771034,
        "HKD": 7.78191949,
        "USD": 1
      };
      this.countryFrom = $("#fromSelect");
      this.countryTo = $("toSelect");
      this.keys = [];
      this.values = [];
      $.ajaxSetup({
        cache: false
      });
      this.retrieveOpenExchangeData();
      return true;
    };

    CurrencyConverter.prototype.retrieveOpenExchangeData = function() {
      return $.ajax({
        url: 'http://openexchangerates.org/latest.json',
        datatype: 'json',
        success: function(data) {
          var fxSetup;
          if ((typeof fx !== "undefined" && fx !== null) && (fx.rates != null)) {
            fx.rates = data.rates;
            fx.base = data.base;
          } else {
            fxSetup = {
              rates: data.rates,
              base: data.base
            };
          }
          if (data.timestamp) {
            $(".data-data").text(this.timeConverter(data.timestamp));
          }
          return this.buildOptionsBox();
        }
      });
    };

    CurrencyConverter.prototype.timeConverter = function() {};

    CurrencyConverter.prototype.buildOptionsBox = function() {};

    CurrencyConverter.prototype.showResults = function() {};

    return CurrencyConverter;

  })();

}).call(this);
